"""empty message

Revision ID: 07905eec755c
Revises: 875c265203d2
Create Date: 2023-04-21 15:10:11.838047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07905eec755c"
down_revision = "875c265203d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("show", sa.Column("title", sa.String(length=200), nullable=True))
    op.execute("UPDATE show SET title = 'nA'  WHERE title IS NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("show", "title")
    # ### end Alembic commands ###
