"""empty message

Revision ID: 875c265203d2
Revises: 1c59a754b24c
Create Date: 2023-04-20 15:12:18.170042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875c265203d2'
down_revision = '1c59a754b24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
